# Generated by Django 4.2.4 on 2023-09-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("dnascimento", models.IntegerField(default=0)),
                ("mascimento", models.CharField(default="null", max_length=10)),
                ("anascimento", models.IntegerField(default=0)),
            ],
        ),
    ]
