# Generated by Django 4.2.4 on 2023-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anascimento",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="dnascimento",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="mascimento",
            field=models.CharField(default="null", max_length=10),
        ),
    ]
